import React, { useEffect } from 'react';
import { Link } from 'react-router-dom';
import './Home.scss';

const Home = (props) => {
    useEffect(() => {
        props.changeHighlight('');
    }, [props]);

    return (
        <div id='home-container'>
            <h2>Add video games to lists!</h2>
            <h3>Your Lists:</h3>
            <ul>
                {props.lists.map(item => {
                    return (
                        <Link to={`/${item.linkRoute}`} key={item.name}>
                            <li>{item.name}</li>
                        </Link>
                    );
                })}
            </ul>
            <hr />
            <p id="image-note"><strong>Note: </strong>Due to the size of images generated by RAWG.io for list tile backgrounds, it is suggested that you turn images off if you're on a mobile device. This option is found in the sidebar menu.</p>
        </div>
    );
};

export default Home;
